google:
  places:
    autocomplete:
        base-url: https://maps.googleapis.com/maps/api/place/autocomplete/json
        api-key: AIzaSyBKAgzBLMAY4mqQIaNM9SGAw4Hnoyr1QJ8
    details:
        base-url: https://maps.googleapis.com/maps/api/place/details/json
        api-key: AIzaSyBKAgzBLMAY4mqQIaNM9SGAw4Hnoyr1QJ8