google:
  api-key: AIzaSyBKAgzBLMAY4mqQIaNM9SGAw4Hnoyr1QJ8
  places:
    autocomplete:
      base-url: https://maps.googleapis.com/maps/api/place/autocomplete/json
    details:
      base-url: https://maps.googleapis.com/maps/api/place/details/json